"""init blog schema

Revision ID: d0cdba026b9a
Revises: 
Create Date: 2026-05-03 13:20:59.738688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd0cdba026b9a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'categories', ['name'])
    op.alter_column('comments', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.create_index(op.f('ix_comments_post_id'), 'comments', ['post_id'], unique=False)
    op.drop_constraint(op.f('fk_comments_post'), 'comments', type_='foreignkey')
    op.drop_constraint(op.f('fk_comments_user'), 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'comments', 'posts', ['post_id'], ['id'])
    op.drop_constraint(op.f('fk_post_tags_tag'), 'post_tags', type_='foreignkey')
    op.drop_constraint(op.f('fk_post_tags_post'), 'post_tags', type_='foreignkey')
    op.create_foreign_key(None, 'post_tags', 'posts', ['post_id'], ['id'])
    op.create_foreign_key(None, 'post_tags', 'tags', ['tag_id'], ['id'])
    op.alter_column('posts', 'title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('posts', 'slug',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('posts', 'content',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('posts', 'status',
               existing_type=mysql.ENUM('draft', 'published'),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'published'"))
    op.alter_column('posts', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.drop_index(op.f('idx_author_id'), table_name='posts')
    op.drop_index(op.f('idx_category_id'), table_name='posts')
    op.drop_index(op.f('idx_slug'), table_name='posts')
    op.drop_index(op.f('idx_title'), table_name='posts')
    op.drop_index(op.f('slug'), table_name='posts')
    op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=False)
    op.create_index(op.f('ix_posts_slug'), 'posts', ['slug'], unique=True)
    op.create_index(op.f('ix_posts_title'), 'posts', ['title'], unique=False)
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'])
    op.create_foreign_key(None, 'posts', 'categories', ['category_id'], ['id'])
    op.drop_column('posts', 'read_time')
    op.drop_column('posts', 'likes')
    op.alter_column('tags', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_index(op.f('email'), table_name='users')
    op.drop_index(op.f('idx_email'), table_name='users')
    op.drop_index(op.f('idx_username'), table_name='users')
    op.drop_index(op.f('username'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('username'), 'users', ['username'], unique=True)
    op.create_index(op.f('idx_username'), 'users', ['username'], unique=False)
    op.create_index(op.f('idx_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('email'), 'users', ['email'], unique=True)
    op.alter_column('users', 'hashed_password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('tags', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.add_column('posts', sa.Column('likes', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('posts', sa.Column('read_time', mysql.VARCHAR(length=20), nullable=False))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_index(op.f('ix_posts_title'), table_name='posts')
    op.drop_index(op.f('ix_posts_slug'), table_name='posts')
    op.drop_index(op.f('ix_posts_id'), table_name='posts')
    op.create_index(op.f('slug'), 'posts', ['slug'], unique=True)
    op.create_index(op.f('idx_title'), 'posts', ['title'], unique=False)
    op.create_index(op.f('idx_slug'), 'posts', ['slug'], unique=False)
    op.create_index(op.f('idx_category_id'), 'posts', ['category_id'], unique=False)
    op.create_index(op.f('idx_author_id'), 'posts', ['author_id'], unique=False)
    op.alter_column('posts', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('posts', 'status',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('draft', 'published'),
               existing_nullable=True,
               existing_server_default=sa.text("'published'"))
    op.alter_column('posts', 'content',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('posts', 'slug',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('posts', 'title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(None, 'post_tags', type_='foreignkey')
    op.drop_constraint(None, 'post_tags', type_='foreignkey')
    op.create_foreign_key(op.f('fk_post_tags_post'), 'post_tags', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_post_tags_tag'), 'post_tags', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(op.f('fk_comments_user'), 'comments', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_comments_post'), 'comments', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_comments_post_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.alter_column('comments', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.drop_constraint(None, 'categories', type_='unique')
    # ### end Alembic commands ###
