"""update post models

Revision ID: e3344375efd1
Revises: f468026cc7ca
Create Date: 2026-05-10 21:20:11.471721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e3344375efd1'
down_revision: Union[str, Sequence[str], None] = 'f468026cc7ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('slug', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'categories', ['slug'])
    op.add_column('posts', sa.Column('likes_count', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('read_time', sa.String(length=50), nullable=True))
    op.add_column('posts', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('posts', 'cover_image',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.alter_column('posts', 'cover_image',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('posts', 'updated_at')
    op.drop_column('posts', 'read_time')
    op.drop_column('posts', 'likes_count')
    op.drop_constraint(None, 'categories', type_='unique')
    op.drop_column('categories', 'slug')
    # ### end Alembic commands ###
