"""fix likes constraints

Revision ID: f468026cc7ca
Revises: d0cdba026b9a
Create Date: 2026-05-03 14:34:20.044931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f468026cc7ca'
down_revision: Union[str, Sequence[str], None] = 'd0cdba026b9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'post_id', name='uq_user_post_like')
    )
    op.create_index('ix_like_user_post', 'likes', ['user_id', 'post_id'], unique=False)
    op.alter_column('categories', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.alter_column('comments', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('posts', 'title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('posts', 'slug',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('posts', 'content',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('posts', 'status',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'published'"))
    op.alter_column('posts', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('posts', 'author_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('tags', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('tags', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('posts', 'author_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('posts', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('posts', 'status',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'published'"))
    op.alter_column('posts', 'content',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('posts', 'slug',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('posts', 'title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('comments', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.alter_column('categories', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_index('ix_like_user_post', table_name='likes')
    op.drop_table('likes')
    # ### end Alembic commands ###
